/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.6.0
 *
 * Project: 'HID.Release+B-U585I-IOT02A' 
 * Target:  'Release+B-U585I-IOT02A' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* ARM::CMSIS-Compiler:STDERR:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDERR                /* CMSIS-Compiler STDERR */
#define RTE_CMSIS_Compiler_STDERR_Custom         /* CMSIS-Compiler STDERR: Custom */
/* ARM::CMSIS-Compiler:STDIN:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDIN                 /* CMSIS-Compiler STDIN */
#define RTE_CMSIS_Compiler_STDIN_Custom          /* CMSIS-Compiler STDIN: Custom */
/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.9.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
#define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* Keil::CMSIS Driver:USART@3.0.0 */
#define RTE_CMSIS_Driver_USART1         /* Driver USART1  */
#define RTE_CMSIS_Driver_USART2         /* Driver USART2  */
#define RTE_CMSIS_Driver_USART3         /* Driver USART3  */
#define RTE_CMSIS_Driver_USART4         /* Driver USART4  */
#define RTE_CMSIS_Driver_USART5         /* Driver USART5  */
#define RTE_CMSIS_Driver_USART6         /* Driver USART6  */
#define RTE_CMSIS_Driver_USART7         /* Driver USART7  */
#define RTE_CMSIS_Driver_USART8         /* Driver USART8  */
#define RTE_CMSIS_Driver_USART9         /* Driver USART9  */
#define RTE_CMSIS_Driver_USART9         /* Driver USART9  */
#define RTE_CMSIS_Driver_USART10        /* Driver USART10 */
#define RTE_CMSIS_Driver_USART11        /* Driver USART11 */
#define RTE_CMSIS_Driver_USART12        /* Driver USART12 */
#define RTE_CMSIS_Driver_USART13        /* Driver USART13 */
#define RTE_CMSIS_Driver_USART14        /* Driver USART14 */
#define RTE_CMSIS_Driver_USART15        /* Driver USART15 */
#define RTE_CMSIS_Driver_USART21        /* Driver USART21 (LPUART1) */
#define RTE_CMSIS_Driver_USART22        /* Driver USART22 (LPUART2) */
#define RTE_CMSIS_Driver_USART23        /* Driver USART23 (LPUART3) */
/* Keil::CMSIS Driver:USB Device@3.0.0 */
#define RTE_Drivers_USBD0               /* Driver USBD0 */
#define RTE_Drivers_USBD1               /* Driver USBD1 */
/* Keil::CMSIS Driver:VIO:Board&B-U585I-IOT02A@2.0.1 */
#define RTE_VIO_BOARD
#define RTE_VIO_B_U585I_IOT02A
/* Keil::Device:CubeMX@1.0.0 */
#define RTE_DEVICE_CUBE_MX
#define CMSIS_device_header "stm32u5xx.h"
/* Keil::USB&MDK:CORE@8.0.0 */
#define RTE_USB_Core                    /* USB Core */
/* Keil::USB&MDK:Device:HID@8.0.0 */
#define RTE_USB_Device_HID_0            /* USB Device HID instance 0 */

/* Keil::USB&MDK:Device@8.0.0 */
#define RTE_USB_Device_0                /* USB Device 0 */



#endif /* RTE_COMPONENTS_H */
